### ISSUE TITLE
ERROR: UndefVarError: eirene not defined

### ISSUE THREAD

**Issue by annaja** [Eetion/Eirene.jl#16]
Hi Eirene team,
I am using a Windows 10 on a PC. 
I went through the steps in the readme and example text files using Julia version 0.6.4, 1.2 and 1.1.1. (example follows)
Version 1.1.1 is the version that runs the instructions without an error message, up to the point that it should compile 'using Eirene'. 
I appreciate your help in resolving this issue in bold bellow.
Cheers,
Anna
@bnels

There are the example steps I took in Julia 1.1.1. with outputs:
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.1 (2019-05-16)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using Pkg

julia> Pkg.add("Eirene")
  Updating registry at `C:\Users\Anna\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
 Installed CSTParser ─ v1.0.0
  Updating `C:\Users\Anna\.julia\environments\v1.1\Project.toml`
 [no changes]
  Updating `C:\Users\Anna\.julia\environments\v1.1\Manifest.toml`
  [00ebfdb7] ↑ CSTParser v0.6.2 ⇒ v1.0.0

julia> Pkg.update()
  Updating registry at `C:\Users\Anna\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `C:\Users\Anna\.julia\environments\v1.1\Project.toml`
 [no changes]
  Updating `C:\Users\Anna\.julia\environments\v1.1\Manifest.toml`
 [no changes]

julia> using Eirene
[ Info: Precompiling Eirene [9c0f25c4-2ca1-5870-89f6-52640788da1d]
WARNING: using HTTP.stack in module Mux conflicts with an existing identifier.
WARNING: Method definition savehtml(IO, PlotlyBase.Plot{TT} where TT<:PlotlyBase.AbstractTrace) in module PlotlyBase at C:\Users\Anna\.julia\packages\PlotlyBase\80KwD\src\output.jl:40 overwritten in module PlotlyJS at C:\Users\Anna\.julia\packages\PlotlyJS\b9Efu\src\display.jl:334.
WARNING: Method definition savehtml(PlotlyBase.Plot{TT} where TT<:PlotlyBase.AbstractTrace, AbstractString) in module PlotlyBase at C:\Users\Anna\.julia\packages\PlotlyBase\80KwD\src\output.jl:52 overwritten in module PlotlyJS at C:\Users\Anna\.julia\packages\PlotlyJS\b9Efu\src\display.jl:361.
WARNING: Method definition savehtml(IO, PlotlyBase.Plot{TT} where TT<:PlotlyBase.AbstractTrace) in module PlotlyBase at C:\Users\Anna\.julia\packages\PlotlyBase\80KwD\src\output.jl:40 overwritten in module PlotlyJS at C:\Users\Anna\.julia\packages\PlotlyJS\b9Efu\src\display.jl:334.
WARNING: Method definition savehtml(PlotlyBase.Plot{TT} where TT<:PlotlyBase.AbstractTrace, AbstractString) in module PlotlyBase at C:\Users\Anna\.julia\packages\PlotlyBase\80KwD\src\output.jl:52 overwritten in module PlotlyJS at C:\Users\Anna\.julia\packages\PlotlyJS\b9Efu\src\display.jl:361.
ERROR: LoadError: ArgumentError: Package Eirene does not have Plotly in its dependencies:
- If you have Eirene checked out for development and have
  added Plotly as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- **Otherwise you may need to report an issue with Eirene**
Stacktrace:
 [1] require(::Module, ::Symbol) at .\loading.jl:836
 [2] include at .\boot.jl:326 [inlined]
 [3] include_relative(::Module, ::String) at .\loading.jl:1038
 [4] include(::Module, ::String) at .\sysimg.jl:29
 [5] top-level scope at none:2
 [6] eval at .\boot.jl:328 [inlined]
 [7] eval(::Expr) at .\client.jl:404
 [8] top-level scope at .\none:3
in expression starting at C:\Users\Anna\.julia\dev\Eirene\src\Eirene.jl:42
ERROR: Failed to precompile Eirene [9c0f25c4-2ca1-5870-89f6-52640788da1d] to C:\Users\Anna\.julia\compiled\v1.1\Eirene\mCiG1.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1197
 [3] _require(::Base.PkgId) at .\loading.jl:960
 [4] require(::Base.PkgId) at .\loading.jl:858
 [5] require(::Module, ::Symbol) at .\loading.jl:853

julia> Eirene.fictionalfunction()
ERROR: UndefVarError: Eirene not defined
Stacktrace:
 [1] top-level scope at none:0

julia> x = rand(3,50)
3×50 Array{Float64,2}:
 0.222454   0.472231   0.261004  0.518287  0.50643   0.206621   …  0.944558   0.7961    0.579084  0.193574  0.675513
 0.591427   0.0845291  0.923597  0.591617  0.758719  0.761218      0.98849    0.476811  0.128794  0.13048   0.85863
 0.0277452  0.191558   0.53545   0.343697  0.999639  0.0714336     0.0247873  0.811825  0.349891  0.498991  0.889964

julia> C = eirene(x,model = "pc")
ERROR: UndefVarError: eirene not defined
Stacktrace:
 [1] top-level scope at none:0

**Comment by henselman-petrusek** [comment]
Thanks for the report and apologies for the slow turn around.  This was a formatting issue with the package requirements, and it should now be resolved.  If you update your packages, all should *hopefully* be well.  Please let us know either way.  Thanks again!

**Comment by annaja** [comment]
I still face errors, even after Pkg.update(). Please see the following:

   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  **Version 1.1.1 (2019-05-16)**
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using Pkg

julia> Pkg.add("Eirene")
  Updating registry at `C:\Users\Anna\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
 Installed ArrayLayouts ────── v0.1.4
 Installed FillArrays ──────── v0.8.1
 Installed FilePathsBase ───── v0.7.0
 Installed CategoricalArrays ─ v0.7.2
 Installed LazyArrays ──────── v0.14.7
 Installed HDF5 ────────────── v0.12.5
 Installed HTTP ────────────── v0.8.8
 Installed Parsers ─────────── v0.3.9
 Installed MacroTools ──────── v0.5.2
 Installed BinaryProvider ──── v0.5.8
 Installed StaticArrays ────── v0.12.1
 Installed CSV ─────────────── v0.5.18
  Updating `C:\Users\Anna\.julia\environments\v1.1\Project.toml`
 [no changes]
  Updating `C:\Users\Anna\.julia\environments\v1.1\Manifest.toml`
  [4c555306] + ArrayLayouts v0.1.4
  [b99e7846] ↑ BinaryProvider v0.5.7 ⇒ v0.5.8
  [00ebfdb7] - CSTParser v1.0.0
  [336ed68f] ↑ CSV v0.5.14 ⇒ v0.5.18
  [324d7699] ↑ CategoricalArrays v0.7.1 ⇒ v0.7.2
  [48062228] ↑ FilePathsBase v0.6.2 ⇒ v0.7.0
  [1a297f60] ↑ FillArrays v0.7.4 ⇒ v0.8.1
  [f67ccb44] ↑ HDF5 v0.12.4 ⇒ v0.12.5
  [cd3eb016] ↑ HTTP v0.8.6 ⇒ v0.8.8
  [5078a376] ↑ LazyArrays v0.12.3 ⇒ v0.14.7
  [1914dd2f] ↑ MacroTools v0.5.1 ⇒ v0.5.2
  [69de0a69] ↑ Parsers v0.3.7 ⇒ v0.3.9
  [90137ffa] ↑ StaticArrays v0.11.1 ⇒ v0.12.1
  [0796e94c] - Tokenize v0.5.6
  Building HDF5 → `C:\Users\Anna\.julia\packages\HDF5\Zh9on\deps\build.log`

julia> Pkg.update()
  Updating registry at `C:\Users\Anna\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `C:\Users\Anna\.julia\environments\v1.1\Project.toml`
 [no changes]
  Updating `C:\Users\Anna\.julia\environments\v1.1\Manifest.toml`
 [no changes]

julia> Eirene.fictionalfunction()
ERROR: UndefVarError: Eirene not defined
Stacktrace:
 [1] top-level scope at none:0

julia> using Eirene
[ Info: Precompiling Eirene [9c0f25c4-2ca1-5870-89f6-52640788da1d]
WARNING: using HTTP.stack in module Mux conflicts with an existing identifier.
WARNING: Method definition savehtml(IO, PlotlyBase.Plot{TT} where TT<:PlotlyBase.AbstractTrace) in module PlotlyBase at C:\Users\Anna\.julia\packages\PlotlyBase\80KwD\src\output.jl:40 overwritten in module PlotlyJS at C:\Users\Anna\.julia\packages\PlotlyJS\b9Efu\src\display.jl:334.
WARNING: Method definition savehtml(PlotlyBase.Plot{TT} where TT<:PlotlyBase.AbstractTrace, AbstractString) in module PlotlyBase at C:\Users\Anna\.julia\packages\PlotlyBase\80KwD\src\output.jl:52 overwritten in module PlotlyJS at C:\Users\Anna\.julia\packages\PlotlyJS\b9Efu\src\display.jl:361.
WARNING: Method definition savehtml(IO, PlotlyBase.Plot{TT} where TT<:PlotlyBase.AbstractTrace) in module PlotlyBase at C:\Users\Anna\.julia\packages\PlotlyBase\80KwD\src\output.jl:40 overwritten in module PlotlyJS at C:\Users\Anna\.julia\packages\PlotlyJS\b9Efu\src\display.jl:334.
WARNING: Method definition savehtml(PlotlyBase.Plot{TT} where TT<:PlotlyBase.AbstractTrace, AbstractString) in module PlotlyBase at C:\Users\Anna\.julia\packages\PlotlyBase\80KwD\src\output.jl:52 overwritten in module PlotlyJS at C:\Users\Anna\.julia\packages\PlotlyJS\b9Efu\src\display.jl:361.
ERROR: LoadError: ArgumentError: Package Eirene does not have Plotly in its dependencies:
- If you have Eirene checked out for development and have
  added Plotly as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with Eirene
Stacktrace:
 [1] require(::Module, ::Symbol) at .\loading.jl:836
 [2] include at .\boot.jl:326 [inlined]
 [3] include_relative(::Module, ::String) at .\loading.jl:1038
 [4] include(::Module, ::String) at .\sysimg.jl:29
 [5] top-level scope at none:2
 [6] eval at .\boot.jl:328 [inlined]
 [7] eval(::Expr) at .\client.jl:404
 [8] top-level scope at .\none:3
in expression starting at C:\Users\Anna\.julia\dev\Eirene\src\Eirene.jl:42
ERROR: Failed to precompile Eirene [9c0f25c4-2ca1-5870-89f6-52640788da1d] to C:\Users\Anna\.julia\compiled\v1.1\Eirene\mCiG1.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1197
 [3] _require(::Base.PkgId) at .\loading.jl:960
 [4] require(::Base.PkgId) at .\loading.jl:858
 [5] require(::Module, ::Symbol) at .\loading.jl:853

**Comment by henselman-petrusek** [comment]
Hi @annaja, thanks for the update.  I'm a bit tied up this week, but here are some things steps that will help diagnosis:  (1) does the problem persist after rebooting? (2) if it does, what version of Eirene is listed in the Project.toml file for the installed package?  Thanks.

**Comment by annaja** [comment]
Hi @Eetion 
Yes, the problem persists. 
Eirene version = "1.3.0"
Thanks

**Comment by henselman-petrusek** [comment]
Hi @annaja,
Great, this is very informative.  The most recent release is version 1.3.1 (you can actually verify this on the official julia package [repo](https://github.com/JuliaRegistries/General/tree/master/E) ).  So it seems that for some reason the package isn't updating.  I haven't encountered this problem before, but one thing to try would be updating from the package manager environment.  Does that have any effect?

**Comment by annaja** [comment]
I am very excited that it's working now! I went through a basic example without any problems. Thank you for your help!

**Comment by annaja** [comment]
for your information, using Eirene came with Warnings:

julia> using Eirene
[ Info: Precompiling Eirene [9c0f25c4-2ca1-5870-89f6-52640788da1d]
WARNING: using HTTP.stack in module Mux conflicts with an existing identifier.
WARNING: Method definition savehtml(IO, PlotlyBase.Plot{TT} where TT<:PlotlyBase.AbstractTrace) in module PlotlyBase at C:\Users\Anna\.julia\packages\PlotlyBase\80KwD\src\output.jl:40 overwritten in module PlotlyJS at C:\Users\Anna\.julia\packages\PlotlyJS\b9Efu\src\display.jl:334.
WARNING: Method definition savehtml(PlotlyBase.Plot{TT} where TT<:PlotlyBase.AbstractTrace, AbstractString) in module PlotlyBase at C:\Users\Anna\.julia\packages\PlotlyBase\80KwD\src\output.jl:52 overwritten in module PlotlyJS at C:\Users\Anna\.julia\packages\PlotlyJS\b9Efu\src\display.jl:361.
WARNING: Method definition savehtml(IO, PlotlyBase.Plot{TT} where TT<:PlotlyBase.AbstractTrace) in module PlotlyBase at C:\Users\Anna\.julia\packages\PlotlyBase\80KwD\src\output.jl:40 overwritten in module PlotlyJS at C:\Users\Anna\.julia\packages\PlotlyJS\b9Efu\src\display.jl:334.
WARNING: Method definition savehtml(PlotlyBase.Plot{TT} where TT<:PlotlyBase.AbstractTrace, AbstractString) in module PlotlyBase at C:\Users\Anna\.julia\packages\PlotlyBase\80KwD\src\output.jl:52 overwritten in module PlotlyJS at C:\Users\Anna\.julia\packages\PlotlyJS\b9Efu\src\display.jl:361.
